# Meta data
name:         wui
authors:      任我行
description:  Build mobile apps with simple HTML, CSS, and JS components.
favicon:      http://gtms04.alicdn.com/tps/i4/TB17MaDGpXXXXb7apXXAz6UFXXX-16-16.png
version:      0.0.1

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
host:         0.0.0.0
port:         4000
